import {
  LayoutDashboard,
  Package,
  Clock,
  Clipboard,
  Users,
  Ship,
  Settings,
  CalendarDays,
  Library,
  CalendarRange,
  ListChecks,
} from 'lucide-react';

export const menuItems = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: <LayoutDashboard className="w-4 h-4" strokeWidth={1.5} />,
    path: '/dashboard',
    hasDropdown: false,
  },
  {
    id: 'planned-maintenance',
    label: 'Planned Maintenance',
    icon: <CalendarDays className="w-4 h-4" strokeWidth={1.5} />,
    hasDropdown: true,
    path: '/planned-maintenance',
  },
  {
    id: 'spares-inventory',
    label: 'Spares Inventory',
    icon: <Package className="w-4 h-4" strokeWidth={1.5} />,
    hasDropdown: true,
    path: '/spares-inventory',
  },
  {
    id: 'machinery-running-hrs',
    label: 'Machinery Running Hrs',
    icon: <Clock className="w-4 h-4" strokeWidth={1.5} />,
    hasDropdown: true,
    path: '/machinery-running-hrs',
  },
  {
    id: 'lube-oil-summary',
    label: 'Lube Oil Summary',
    icon: <Clipboard className="w-4 h-4" strokeWidth={1.5} />,
    hasDropdown: true,
    path: '/lube-oil-summary',
  },
  {
    id: 'library',
    label: 'Library',
    icon: <Library className="w-4 h-4" strokeWidth={1.5} />,
    hasDropdown: true,
    path: '/library',
  },
  {
    id: 'pms-calendar',
    label: 'PMS Calendar',
    icon: <CalendarRange className="w-4 h-4" strokeWidth={1.5} />,
    hasDropdown: false,
    path: '/pms-calendar',
  },
  {
    id: 'user-management-roles',
    label: 'User Management Roles',
    icon: <Users className="w-4 h-4" strokeWidth={1.5} />,
    hasDropdown: true,
    path: '/user-management-roles',
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: <ListChecks className="w-4 h-4" strokeWidth={1.5} />,
    hasDropdown: true,
    path: '/reports',
  },
  {
    id: 'fleet-management',
    label: 'Fleet Management',
    icon: <Ship className="w-4 h-4" strokeWidth={1.5} />,
    path: '/fleet-management',
    hasDropdown: false,
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: <Settings className="w-4 h-4" strokeWidth={1.5} />,
    hasDropdown: true,
    path: '/settings',
  },
];
